### ISSUE TITLE
Zimbra + alfresco integration

### ISSUE THREAD

**Issue by sureshdba2003** [fcorti/CMIS-Input-plugin#3]
Hi,

I am using zimbra 8.0.8_GA_6184 and alfresco community 5.0. we need to integrate zimbra with alfresco. lets any zimlets or script to integrate with both open sources?

Best regards, 
Suresh

**Comment by fcorti** [comment]
Hi Sureh,

I think this is an out of topic here in this module.
I close the issue and reply to you privately.

Best regards,

-F
